#ifndef REPORTERROR_HPP
#define REPORTERROR_HPP
#include <stdio.h>
enum INFO {
    OK = 0, T1_VAR_USED_NO_DEF, T2_FUNC_USED_NO_DEF,
    T3_VAR_REDEF, T4_FUNC_REDEF, T5_UNMATCH_TYPE_ASSIGN,
    T6_RVAL_ON_ASSIGN_LEFT, T7_UNMATCH_OPERANDS,
    T8_FUNC_RETURN_UNMATCH_DECLARED, T9_FUNC_ARGS_UNMATCH_DECLARED,
    T10_INDEXING_ON_NON_ARRAY, T11_INVOKE_NON_FUNC,
    T12_INDEX_NOT_INTEGER, T13_ACCESS_MEMBER_NON_STRUCTURE,
    T14_ACCESS_NONDEF_STRUCTURE_MEMBER, T15_STRUCTURE_REDEF
};

void reportError(FILE *out, int INFO_type, int lineno);

#endif